import { useState } from "react";

const initialForm = {
    fullName: "",
    email: ""
};

function CreateStudent({
    onSubmit,
    onCancel
}) {
    const [form, setForm] = useState(initialForm);
    const [error, setError] = useState("");

    function handleChange(event) {
        setForm(previous => ({
            ...previous,
            [event.target.name]: event.target.value
        }));
    }

    function submitForm(event) {
        event.preventDefault();

        if (!form.fullName.trim()) {
            setError("Full name is required.");
            return;
        }

        if (!form.email.trim()) {
            setError("Email is required.");
            return;
        }

        setError("");

        onSubmit({
            fullName: form.fullName.trim(),
            email: form.email.trim()
        });

        setForm(initialForm);
    }

    return (
        <form
            onSubmit={submitForm}
            className="flex flex-col gap-5"
        >
            <h1 className="text-3xl font-bold text-center">
                Create Student
            </h1>

            {error && (
                <div className="bg-red-500 text-white p-3 rounded-xl">
                    {error}
                </div>
            )}

            <div>
                <label className="font-bold">
                    Full Name
                </label>

                <input
                    name="fullName"
                    type="text"
                    placeholder="Student full name"
                    value={form.fullName}
                    onChange={handleChange}
                    className="border-2 p-2 w-full rounded-xl"
                />
            </div>

            <div>
                <label className="font-bold">
                    Email
                </label>

                <input
                    name="email"
                    type="email"
                    placeholder="student@example.com"
                    value={form.email}
                    onChange={handleChange}
                    className="border-2 p-2 w-full rounded-xl"
                />
            </div>

            <div className="bg-yellow-100 text-yellow-800 p-3 rounded-xl">
                The initial password will be generated by the
                backend when authentication is implemented.
            </div>

            <div className="flex gap-3">

                <button
                    type="submit"
                    className="flex-1 bg-black text-white py-3 rounded-xl font-bold"
                >
                    Create Student
                </button>

                <button
                    type="button"
                    onClick={onCancel}
                    className="flex-1 bg-gray-300 py-3 rounded-xl font-bold"
                >
                    Cancel
                </button>

            </div>

        </form>
    );
}

export default CreateStudent;

